-- Flyway Migration V1: Initial IAM Schema
-- Aligns database objects with core-platform JPA entities.

CREATE TABLE IF NOT EXISTS iam_module (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    tenant_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    last_modified_at TIMESTAMP,
    last_modified_by VARCHAR(100),
    version BIGINT,
    CONSTRAINT uk_iam_module_code_tenant UNIQUE (code, tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_iam_module_tenant ON iam_module(tenant_id);

CREATE TABLE IF NOT EXISTS iam_resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    module_id BIGINT NOT NULL,
    tenant_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    last_modified_at TIMESTAMP,
    last_modified_by VARCHAR(100),
    version BIGINT,
    CONSTRAINT fk_iam_resource_module FOREIGN KEY (module_id) REFERENCES iam_module(id),
    CONSTRAINT uk_iam_resource_code_tenant UNIQUE (code, tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_iam_resource_tenant ON iam_resource(tenant_id);
CREATE INDEX IF NOT EXISTS idx_iam_resource_module ON iam_resource(module_id);

CREATE TABLE IF NOT EXISTS iam_action (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    tenant_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    last_modified_at TIMESTAMP,
    last_modified_by VARCHAR(100),
    version BIGINT,
    CONSTRAINT uk_iam_action_code_tenant UNIQUE (code, tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_iam_action_tenant ON iam_action(tenant_id);

CREATE TABLE IF NOT EXISTS iam_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    resource_id BIGINT NOT NULL,
    tenant_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    last_modified_at TIMESTAMP,
    last_modified_by VARCHAR(100),
    version BIGINT,
    CONSTRAINT fk_iam_field_resource FOREIGN KEY (resource_id) REFERENCES iam_resource(id),
    CONSTRAINT uk_iam_field_name_resource_tenant UNIQUE (name, resource_id, tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_iam_field_tenant ON iam_field(tenant_id);
CREATE INDEX IF NOT EXISTS idx_iam_field_resource ON iam_field(resource_id);

CREATE TABLE IF NOT EXISTS iam_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    tenant_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    last_modified_at TIMESTAMP,
    last_modified_by VARCHAR(100),
    version BIGINT,
    CONSTRAINT uk_iam_role_name_tenant UNIQUE (name, tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_iam_role_tenant ON iam_role(tenant_id);

CREATE TABLE IF NOT EXISTS iam_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    last_modified_at TIMESTAMP,
    last_modified_by VARCHAR(100),
    version BIGINT,
    CONSTRAINT uk_iam_user_username_tenant UNIQUE (username, tenant_id),
    CONSTRAINT uk_iam_user_email_tenant UNIQUE (email, tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_iam_user_tenant ON iam_user(tenant_id);
CREATE INDEX IF NOT EXISTS idx_iam_user_email ON iam_user(email);

CREATE TABLE IF NOT EXISTS iam_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    module_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    action_id BIGINT NOT NULL,
    field_id BIGINT,
    tenant_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    last_modified_at TIMESTAMP,
    last_modified_by VARCHAR(100),
    version BIGINT,
    CONSTRAINT fk_iam_permission_role FOREIGN KEY (role_id) REFERENCES iam_role(id) ON DELETE CASCADE,
    CONSTRAINT fk_iam_permission_module FOREIGN KEY (module_id) REFERENCES iam_module(id),
    CONSTRAINT fk_iam_permission_resource FOREIGN KEY (resource_id) REFERENCES iam_resource(id),
    CONSTRAINT fk_iam_permission_action FOREIGN KEY (action_id) REFERENCES iam_action(id),
    CONSTRAINT fk_iam_permission_field FOREIGN KEY (field_id) REFERENCES iam_field(id)
);

CREATE INDEX IF NOT EXISTS idx_iam_permission_role ON iam_permission(role_id);
CREATE INDEX IF NOT EXISTS idx_iam_permission_tenant ON iam_permission(tenant_id);

CREATE TABLE IF NOT EXISTS iam_user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_iam_user_roles_user FOREIGN KEY (user_id) REFERENCES iam_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_iam_user_roles_role FOREIGN KEY (role_id) REFERENCES iam_role(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_iam_user_roles_user ON iam_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_iam_user_roles_role ON iam_user_roles(role_id);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(100),
    entity VARCHAR(255),
    entity_id VARCHAR(255),
    user_id VARCHAR(100),
    tenant_id VARCHAR(100),
    occurred_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log(action);
CREATE INDEX IF NOT EXISTS idx_audit_log_tenant ON audit_log(tenant_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_user ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_occurred_at ON audit_log(occurred_at DESC);
